### ISSUE TITLE
"Cannot read property 'substring' of undefined" in keepThreeDecimals()

### ISSUE THREAD

**Issue by inchakov** [inchakov/recipe-parser#4]
The error happened on processing recipe from https://www.allrecipes.com/recipe/231660/pretty-cake-pops/

```
TypeError: Cannot read property 'substring' of undefined
    at keepThreeDecimals (/Users/alekseyinchakov/Projects/git/recipes-crawler/node_modules/recipe-ingredient-parser/lib/convert.js:65:61)
    at Object.convertFromFraction (/Users/alekseyinchakov/Projects/git/recipes-crawler/node_modules/recipe-ingredient-parser/lib/convert.js:10:16)
    at Object.parse (/Users/alekseyinchakov/Projects/git/recipes-crawler/node_modules/recipe-ingredient-parser/lib/index.js:32:24)
    at parseIngredient (/Users/alekseyinchakov/Projects/git/recipes-crawler/dist/index.js:81:43)
    at /Users/alekseyinchakov/Projects/git/recipes-crawler/dist/index.js:73:107
    at Array.map (<anonymous>)
    at parseRecipe (/Users/alekseyinchakov/Projects/git/recipes-crawler/dist/index.js:73:68)
    at Object.callback (/Users/alekseyinchakov/Projects/git/recipes-crawler/dist/index.js:39:34)
    at Crawler._injected (/Users/alekseyinchakov/Projects/git/recipes-crawler/node_modules/crawler/lib/crawler.js:413:10)
    at Crawler._inject (/Users/alekseyinchakov/Projects/git/recipes-crawler/node_modules/crawler/lib/crawler.js:149:3)
```

**Comment by inchakov** [comment]
Fixed use case when decimal reminder is not available
